In [1]:
import numpy as np

# Funções úteis

.cumprod()
.cumsum()
.min()
.max()
.std()
.mean()
.prod()
.sort()
.sum()
.argmax()
.argmin()
.argsort()

## .min()   Menor valor

In [21]:
array = np.arange(10)
display(array)
array.min()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0

## .argmin() Menor Vvalor

In [26]:
array = np.arange(10, 100, 10) 
display(array)
array.argmin()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

0

## .max()  Maior valor

In [18]:
array = np.arange(10)
display(array)
array.max()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

9

## .argmax()  Índice do maior valor

In [20]:
array = np.arange(10, 100, 10) 
display(array)
array.argmax()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

8

## .sum()  Soma de todos os valores

In [10]:
array = np.arange(10)
display(array)
array.sum()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

45

## .prod()  Produto entre todos os valores

In [12]:
array = np.arange(10) + 1
display(array)
array.prod()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3628800

## .mean()  Média dos valores

In [15]:
array = np.arange(10)
display(array)
array.mean()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.5

## .std() Desvio Padrão

In [17]:
array = np.arange(10)
display(array)
array.std()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.8722813232690143

## .cumsum()  Soma acumulativa

In [27]:
array = np.arange(10)
display(array)
array.cumsum()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

## .cumprod() Multiplicação cumulativa!

In [29]:
array = np.arange(10) + 1
display(array) 
array.cumprod()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

# Funções do Pacote

## Ceil e Floor

In [33]:
array = np.linspace(0, 4.9, 50)
array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [34]:
np.ceil(array)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [36]:
np.floor(array)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

## Reciprocal

In [39]:
array = np.arange(10, dtype=float) + 1
display(array)
np.reciprocal(array)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

## Power

In [40]:
array = np.arange(10)
display(array)
np.power(array, 2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

## Median

In [43]:
array = np.array([30, 65, 70, 80, 95, 10, 50, 90, 60])
array = array.reshape(3, 3)
array

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [44]:
np.median(array)

65.0

In [45]:
np.median(array, axis=0)

array([50., 90., 60.])

In [46]:
np.median(array, axis=1)

array([65., 80., 60.])

# Variance

In [55]:
array = np.arange(4)
display(array)
np.var(array)

array([0, 1, 2, 3])

1.25

# Average

In [50]:
array = np.arange(10) + 1
display(array)
array_weights = np.arange(10, 0, -1)
display(array_weights)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [51]:
np.average(array, weights=array_weights)

4.0

In [54]:
p = (array * array_weights).sum()
p /= array_weights.sum()

print(p)


4.0
