# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [14]:
import numpy as np
import time

In [17]:
lista = list(range(1000000))
array = np.arange(1000000)

In [23]:
%%time
lista2 = []
for i in lista:
    lista2.append(i * 2)

Wall time: 15 ms


In [24]:
%%time
array2 = array * 2

Wall time: 3.03 ms


### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [28]:
arrayex2 = np.arange(10)

In [60]:
arrayex2[5:8] = 0
arrayex2

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

### Exercício 3

In [61]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [70]:
arrayex3 = np.arange(12).reshape(2,2,3)

In [72]:
arrayex3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [71]:
arrayex3[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

### Exercício 4

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [76]:
arrayex4 = np.random.rand(9).reshape(3,3)

In [77]:
arrayex4

array([[0.32533934, 0.16655123, 0.31970393],
       [0.65825297, 0.64224464, 0.34610688],
       [0.97344693, 0.90516328, 0.07403514]])

In [83]:
arrayex4[2]

array([0.97344693, 0.90516328, 0.07403514])

In [90]:
arrayex4[:2, 1:]

array([[0.16655123, 0.31970393],
       [0.64224464, 0.34610688]])

### Exercício 5

In [93]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [101]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [102]:
import pandas as pd

In [117]:
x = pd.Series(xarr)
y = pd.Series(yarr)
c = pd.Series(cond)

In [118]:
x[c]

0    1.1
2    1.3
3    1.4
dtype: float64

In [119]:
y[~c]

1    2.2
4    2.5
dtype: float64

In [130]:
x[c].combine(y[~c], max, fill_value=0)

0    1.1
1    2.2
2    1.3
3    1.4
4    2.5
dtype: float64

### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [139]:
arraya = np.arange(10)
np.save('arraya.npy', arraya)

In [140]:
arrayb = np.load("arraya.npy")

In [141]:
arrayb

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [143]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [144]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [147]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

In [151]:
data = resp.json()
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35964',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35964/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35964/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35964/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/35964',
 'id': 688340457,
 'node_id': 'MDExOlB1bGxSZXF1ZXN0NDc1NjI5MDk3',
 'number': 35964,
 'title': 'BUG/CLN: Decouple Series/DataFrame.transform',
 'user': {'login': 'rhshadrach',
  'id': 45562402,
  'node_id': 'MDQ6VXNlcjQ1NTYyNDAy',
  'avatar_url': 'https://avatars1.githubusercontent.com/u/45562402?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/rhshadrach',
  'html_url': 'https://github.com/rhshadrach',
  'followers_url': 'https://api.github.com/users/rhshadrach/followers',
  'following_url': 'https://api.git

In [152]:
data[0]['title']

'BUG/CLN: Decouple Series/DataFrame.transform'

In [153]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    35964       BUG/CLN: Decouple Series/DataFrame.transform   
1    35963               TYP: misc cleanup in core\generic.py   
2    35961  BUG: Unable to add np.timedelta64 + pd.Interva...   
3    35960      TYP: annotate plotting based on _get_axe_freq   
4    35958  BUG: read_table raises ValueError when delim_w...   
5    35957  TYP: Remove NDFrame._add_series_or_dataframe_o...   
6    35954               TYP: misc typing cleanups for #32911   
7    35953               TYP: misc typing cleanups for #29116   
8    35951                       Gh35889 groupby dropna apply   
9    35948  DOC: "engine=odf" option should ask you to ins...   
10   35947            paste_windows() wrong arg for c_wchar_p   
11   35946  CLN: resolve UserWarning in `pandas/plotting/_...   
12   35945  CLN: UserWarning in `pandas/plotting/_matplotl...   
13   35944         Version Number correction in to_json table   
14   35943  CLN: resolve DeprecationWarning in `pandas/_te...   
15   35942              CLN: DeprecationWarning in `_testing`   
16   35941  DOC: complement the documentation for pandas.D...   
17   35940  BUG:Pandas 1.0.3 → 1.1.1 behavior change on Da...   
18   35939                   TYP: annotations in core.groupby   
19   35938        REGR: Don't set Interval __array_priority__   
20   35937         BUG: BlockSlider not clearing index._cache   
21   35936  REGR: Fix inplace updates on column to set cor...   
22   35934  BUG: Inconsistency in `pd.to_datetime` with `o...   
23   35933                                   TYP: Annotations   
24   35932                 BUG:Installation errors on aarch64   
25   35931  BUG: breaking change in df.replace() from 1.0....   
26   35928  WIP: inconsistencies between python/cython gro...   
27   35925  CLN remove unnecessary trailing commas to get ...   
28   35924  REF: use BlockManager.apply for DataFrameGroup...   
29   35923  BUG: Inconsistent results using pd.json_normal...   

                                               labels state  
0   [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
1   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
6   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
7   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
8   [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
9   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
10                                                 []  open  
11  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
12  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
13                                                 []  open  
14                                                 []  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
19  [{'id': 150096370, 'node_id': 'MDU6TGFiZWwxNTA...  open  
20                                                 []  open  
21  [{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 150096370, 'node_id': 'MDU6TGFiZWwxNTA...  open  
26                                                 []  open  
27  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
28                                                 []  open  
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open

### Exercício 10

In [157]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
con = sqlite3.connect('teste.db')
cur = con.cursor()
sql = 'CREATE TABLE IF NOT EXISTS teste'\
'(id integer primary key, '\
'nome varchar(100), '\
'categoria varchar(50), '\
'descricao varchar(100), '\
'tipo integer)'
cur.execute(sql)
con.commit()



In [163]:
sql = 'INSERT INTO teste VALUES (?, ?, ?, ?, ?)'
dados = [(10, 'teste 1', 'cat1', 'desc1', 6),
        (20, 'teste 2', 'cat1', 'desc2', 4),
        (30, 'teste 3', 'cat1', 'desc3', 2)]
con.executemany(sql, dados)
con.commit()

In [164]:
sql = 'SELECT * FROM TESTE'
df = pd.read_sql_query(sql,con)
df

id     nome categoria descricao  tipo
0   1  teste 1      cat1     desc1     6
1  10  teste 1      cat1     desc1     6
2  20  teste 2      cat1     desc2     4
3  30  teste 3      cat1     desc3     2

In [165]:
cur.close()
con.close()

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>